services:
    app:
        container_name: shoutrrr
        restart: unless-stopped
        working_dir: /var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - shoutrrr

networks:
    shoutrrr:
        name: shoutrrr
        driver: bridge
        external: false
